#!/bin/bash
#
# Suzerain Installation Script
# One command to get everything working.
#
# Usage: ./scripts/install.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Suzerain Installation${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# -----------------------------------------------------------------------------
# 1. Check Python version (3.11+)
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[1/7] Checking Python version...${NC}"

PYTHON_CMD=""
for cmd in python3.12 python3.11 python3 python; do
    if command -v "$cmd" &> /dev/null; then
        version=$("$cmd" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 11 ]; then
            PYTHON_CMD="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo -e "${RED}Error: Python 3.11+ required${NC}"
    echo "Install with: brew install python@3.11"
    exit 1
fi

echo -e "${GREEN}  Found: $PYTHON_CMD (version $version)${NC}"

# -----------------------------------------------------------------------------
# 2. Create virtual environment if not exists
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[2/7] Setting up virtual environment...${NC}"

VENV_DIR="$PROJECT_ROOT/.venv"

if [ -d "$VENV_DIR" ]; then
    echo -e "${GREEN}  Virtual environment exists at .venv${NC}"
else
    echo "  Creating virtual environment..."
    "$PYTHON_CMD" -m venv "$VENV_DIR"
    echo -e "${GREEN}  Created .venv${NC}"
fi

# Activate venv
source "$VENV_DIR/bin/activate"

# -----------------------------------------------------------------------------
# 3. Install dependencies from pyproject.toml
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[3/7] Installing Python dependencies...${NC}"

pip install --upgrade pip -q
pip install -e "$PROJECT_ROOT[dev,wakeword,deepgram]" -q

echo -e "${GREEN}  Dependencies installed${NC}"

# -----------------------------------------------------------------------------
# 4. Check for required system deps (portaudio via brew)
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[4/7] Checking system dependencies...${NC}"

MISSING_DEPS=()

# Check for Homebrew
if ! command -v brew &> /dev/null; then
    echo -e "${RED}Error: Homebrew not found${NC}"
    echo "Install from: https://brew.sh"
    exit 1
fi

# Check for portaudio (required for pyaudio)
if ! brew list portaudio &> /dev/null; then
    MISSING_DEPS+=("portaudio")
fi

if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
    echo "  Installing missing dependencies: ${MISSING_DEPS[*]}"
    brew install "${MISSING_DEPS[@]}"
fi

echo -e "${GREEN}  System dependencies OK${NC}"

# -----------------------------------------------------------------------------
# 5. Prompt for API keys
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[5/7] Setting up API keys...${NC}"

ENV_FILE="$PROJECT_ROOT/.env"

# Function to prompt for key
prompt_key() {
    local key_name="$1"
    local description="$2"
    local required="$3"
    local current_value=""

    # Check if already set in .env
    if [ -f "$ENV_FILE" ]; then
        current_value=$(grep "^${key_name}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
    fi

    if [ -n "$current_value" ]; then
        echo -e "  ${key_name}: ${GREEN}already set${NC}"
        return
    fi

    echo ""
    echo -e "  ${BLUE}$description${NC}"

    if [ "$required" = "required" ]; then
        while true; do
            read -rp "  Enter $key_name: " value
            if [ -n "$value" ]; then
                echo "${key_name}=${value}" >> "$ENV_FILE"
                echo -e "  ${GREEN}Saved${NC}"
                break
            else
                echo -e "  ${RED}Required. Please enter a value.${NC}"
            fi
        done
    else
        read -rp "  Enter $key_name (or press Enter to skip): " value
        if [ -n "$value" ]; then
            echo "${key_name}=${value}" >> "$ENV_FILE"
            echo -e "  ${GREEN}Saved${NC}"
        else
            echo -e "  ${YELLOW}Skipped${NC}"
        fi
    fi
}

# Create .env if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    touch "$ENV_FILE"
    echo "# Suzerain API Keys" > "$ENV_FILE"
    echo "# Generated by install.sh" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
fi

# Deepgram API key (required for STT)
prompt_key "DEEPGRAM_API_KEY" "Deepgram API key for speech-to-text (get one at https://console.deepgram.com)" "required"

# Picovoice access key (optional, for wake word)
prompt_key "PICOVOICE_ACCESS_KEY" "Picovoice access key for wake word detection (optional, get one at https://console.picovoice.ai)" "optional"

echo ""

# -----------------------------------------------------------------------------
# 6. Add .env to .gitignore if not there
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[6/7] Checking .gitignore...${NC}"

GITIGNORE="$PROJECT_ROOT/.gitignore"

if [ -f "$GITIGNORE" ]; then
    if grep -q "^\.env$" "$GITIGNORE"; then
        echo -e "${GREEN}  .env already in .gitignore${NC}"
    else
        echo ".env" >> "$GITIGNORE"
        echo -e "${GREEN}  Added .env to .gitignore${NC}"
    fi
else
    echo ".env" > "$GITIGNORE"
    echo -e "${GREEN}  Created .gitignore with .env${NC}"
fi

# -----------------------------------------------------------------------------
# 7. Run test suite to verify
# -----------------------------------------------------------------------------
echo -e "${YELLOW}[7/7] Running test suite...${NC}"
echo ""

cd "$PROJECT_ROOT"

if pytest tests/ -v --tb=short; then
    echo ""
    echo -e "${GREEN}All tests passed!${NC}"
else
    echo ""
    echo -e "${YELLOW}Warning: Some tests failed. This may be OK for initial setup.${NC}"
fi

# -----------------------------------------------------------------------------
# Success message
# -----------------------------------------------------------------------------
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Installation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${BLUE}Usage:${NC}"
echo ""
echo "  # Activate the environment"
echo "  source .venv/bin/activate"
echo ""
echo "  # Or use the run script"
echo "  ./scripts/run.sh --test              # Test mode (type commands)"
echo "  ./scripts/run.sh                     # Voice mode (push-to-talk)"
echo "  ./scripts/run.sh --wake              # Voice mode (wake word)"
echo "  ./scripts/run.sh --list              # List all grimoire commands"
echo "  ./scripts/run.sh --sandbox           # Dry run mode"
echo ""
echo -e "${BLUE}Quick test:${NC}"
echo "  ./scripts/run.sh --test --sandbox"
echo "  > the evening redness in the west"
echo ""
echo -e "${YELLOW}\"Whatever exists without my knowledge exists without my consent.\"${NC}"
echo ""
